# Use an official Node.js runtime as a base image

FROM node:20.10.0-alpine

 

# Set the working directory to /app

WORKDIR /app

 

# Copy package.json and package-lock.json to the working directory

COPY package*.json ./

 

# Install app dependencies

RUN npm install

 

# Copy the remaining application code to the working directory

COPY . .

 

# ARG NODE_ENV=development

# ENV NODE_ENV=${NODE_ENV}

 

RUN NODE_ENV=development npm i

 

# Build the Next app

RUN npm run build

 

# Expose the port that the app will run on

EXPOSE 3000

 

# Command to run the application

CMD ["npm", "run", "dev"]